# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build

  # Executes a single TCK test with qpid-jms against ActiveMQ Artemis to demonstrate the scripts work.
  # https://github.com/artemiscloud/activemq-artemis-broker-image
  # https://github.com/apache/qpid-jms
  run-single:

    runs-on: ubuntu-latest

    env:
      artemis_image: quay.io/artemiscloud/activemq-artemis-broker:snapshot

    steps:
    - uses: actions/checkout@v3

    - name: Start Artemis Broker in the background
      run: |
        podman pull ${{env.artemis_image}}
        podman run -p 5672:5672 -e AMQ_USER=tckuser -e AMQ_PASSWORD=tckuser --rm -it ${{env.artemis_image}} &

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Prepare and configure TCKs with Gradle (but don't run it all)
      uses: gradle/gradle-build-action@v2
      with:
        arguments: prepareTckTask --scan

    - name: Run a single TCK test
      run: |
        ant_bin=$PWD/build/apache-ant-1.10.12/bin/ant

        cd build/messaging-tck/src/com/sun/ts/tests/jms/core
        ${ant_bin} -Dtest.client=queuetests/QueueTests.java -Dtest=temporaryQueueNotConsumableTest_from_standalone runclient
